**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [4]:
# Creating a vector with all elements in it as zero
a = np.zeros((10))

# Changing value to 1 at index 5
a[4] = 1

# Printing the resultant array
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
# Asking input from users about the shape of the array
rows = int(input("Enter total number of rows : "))
columns = int(input("Enter total number of columns : "))

# Creating ramdom array
array = np.random.random((rows,columns))

# Printing array
print(array)

Enter total number of rows : 6
Enter total number of columns : 6
[[0.12844178 0.21543167 0.68923726 0.12248286 0.18252561 0.75590673]
 [0.65943994 0.72598644 0.17246623 0.28587126 0.67557737 0.08850352]
 [0.0378457  0.09092659 0.81508969 0.25374552 0.33887252 0.46750775]
 [0.78522938 0.50161044 0.13259682 0.75973194 0.09127194 0.69671137]
 [0.71444856 0.45121497 0.7575236  0.51709686 0.45863475 0.92057244]
 [0.81201016 0.38747399 0.19995676 0.56094303 0.70690266 0.31936458]]


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [7]:
# Taking input from users about the shape of the array
rows = int(input("Enter number of rows : "))
columns = int(input("Enter number of columns : "))

# Creating array using np.ones() with dimensions specified by user
array = np.ones((rows,columns))

# Replacing internal elements with zero
array[1:-1,1:-1] = 0

# Printing resultant array
print(array)

Enter number of rows : 7
Enter number of columns : 7
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [8]:
# Creating desired vector
vector = np.linspace(0,1,12)[1:-1]

# Printing array
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [9]:
# No we cannot create identity matrix of shape (3,4) because identity matrix is always of sphape columns=rows that is square matrix but here the given shape if (3,4)

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [10]:
# Creating zero matrix of 5x5 shape
matrix = np.zeros((5,5))

# Adding array [0,1,2,3,4] to each row
matrix = matrix + np.array([0,1,2,3,4])

# Printing resultant matrix
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [12]:
# Creating vector of shape(10,2) which contains random integers
vector = np.random.randint(1,100,20).reshape(10,2)

# Taking input of coordinates from user
x = int(input("Enter the value of x coordinate : "))
y = int(input("Enter the value of y coordinate : "))

# Converting the coordinate values into numpy array
point = np.array([x,y])

# Calculating distance array
distances_array = np.linalg.norm(vector-point,axis=1)

# Printing distances array
print(distances_array)

Enter the value of x coordinate : 8
Enter the value of y coordinate : 6
[ 44.20407221 112.29425631  54.81788029  30.01666204  83.60023923
  84.          89.96110271  90.25519376  78.16009212  49.76946855]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
# Creating an array with shape(6,7,8)
array = np.random.randint(1,100,336).reshape(6,7,8)

# Calculating 100th element
index = np.unravel_index(100,(6,7,8))

# Printing index
print(index)

(1, 5, 4)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [20]:
# Space separated numbers which needs to be sorted in reverse order of dtype float
numbers = '1 2 3 4 -8 -10'
numbers = np.array(numbers.split(),dtype=np.float)

# Reversing the array
reverse_sorted_array = np.sort(numbers)

# Printing reverse_sorted_array
print(reverse_sorted_array)

[-10.  -8.   1.   2.   3.   4.]


<ipython-input-20-a9a48e363deb>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  numbers = np.array(numbers.split(),dtype=np.float)


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [21]:
# Sample array of which element count operation needs to be performed
array = np.array([1,2,3,4,5])

# Print elements count
print(array.size)

5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [32]:
# Input list
lst = [86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318]

# Converting list into array to make out task easier
input = np.array(lst)

# Calculating softmax function result
e_x = np.exp(input - np.max(input))
softmax_result = e_x / e_x.sum(axis=0)

# Printing softmax function result
print(softmax_result)

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [66]:
# Creating function which can vertically stack any numpy arrays given as input
def vertical_stacking(*args):

  # First checking if all the inputs are numpy arrays or not . If not we will raise error
  for i in args:
    if not isinstance(i,np.ndarray):
      raise ValueError


  # Stacking arrays vertically
  ans = np.vstack(args)

  # Returning arrays
  return ans


# Input arrays that will be send to function

# Array-1
arr1 = np.random.randint(1,100,25).reshape(5,5)

# Array-2
arr2 = np.random.randint(1,100,25).reshape(5,5)


# Function call
vertical_stacking(arr1,arr2)

array([[19, 42, 12, 26, 65],
       [ 4, 92, 69, 29, 21],
       [21, 42, 28, 36, 70],
       [83, 73, 52, 98,  4],
       [34, 94, 65,  9, 11],
       [ 5, 55, 29, 92, 56],
       [47, 49, 13, 15, 94],
       [66, 25, 14, 70, 10],
       [46,  8, 76, 49, 81],
       [93, 81, 39, 37, 60]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [80]:
# Creating function that will calculate all dates bw given dates
def date_array(start_date , end_date):


  # Converting input dates from string format to numpy datetime format
  start_date = np.array(start_date,dtype=np.datetime64)
  end_date = np.array(end_date,dtype=np.datetime64)


  # Calculating dates b/w given dates
  dates = start_date + np.arange((end_date - start_date) + 1)

  # Returning dates
  return dates


# Function calls
date_array('2024-09-02','2024-09-12')

array(['2024-09-02', '2024-09-03', '2024-09-04', '2024-09-05',
       '2024-09-06', '2024-09-07', '2024-09-08', '2024-09-09',
       '2024-09-10', '2024-09-11', '2024-09-12'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [78]:
# Creating input matrix
matrix = np.random.randint(1,100,36).reshape(6,6)

In [64]:
# Printing matrix
print(matrix)
print('\n\n')

# print rowise means
print(np.mean(matrix,axis=1))
print('\n\n')

# Subtracting matrix rowise with roe mean
matrix - np.mean(matrix,axis=1 , keepdims=True)

[[51 66 47 73 46 54]
 [31 93 62 95  7 32]
 [83 43 76 64 62 67]
 [29 71 23 45 74 65]
 [37 18 41 58 38 99]
 [ 2 93 96 59 39 52]]



[56.16666667 53.33333333 65.83333333 51.16666667 48.5        56.83333333]





array([[ -5.16666667,   9.83333333,  -9.16666667,  16.83333333,
        -10.16666667,  -2.16666667],
       [-22.33333333,  39.66666667,   8.66666667,  41.66666667,
        -46.33333333, -21.33333333],
       [ 17.16666667, -22.83333333,  10.16666667,  -1.83333333,
         -3.83333333,   1.16666667],
       [-22.16666667,  19.83333333, -28.16666667,  -6.16666667,
         22.83333333,  13.83333333],
       [-11.5       , -30.5       ,  -7.5       ,   9.5       ,
        -10.5       ,  50.5       ],
       [-54.83333333,  36.16666667,  39.16666667,   2.16666667,
        -17.83333333,  -4.83333333]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [54]:
# Creating input array
array = np.random.randint(1,100,36).reshape(6,6)

# Printing array before swap
print("Array before columns swap \n\n")
print(array,'\n\n')

# Swapping columns 0 and 1
array[:,[0,1]] = array[:,[1,0]]

# Print new array
print("Array after columns swap\n\n")
print(array)

Array before columns swap 


[[78 57 22 30  2 25]
 [36 77 75 73 10 52]
 [47 23 90  6  8 66]
 [16 15 28 75 77 46]
 [78 28 19 54 72 27]
 [70 24 70  8 26 43]] 


Array after columns swap


[[57 78 22 30  2 25]
 [77 36 75 73 10 52]
 [23 47 90  6  8 66]
 [15 16 28 75 77 46]
 [28 78 19 54 72 27]
 [24 70 70  8 26 43]]


###`Q-16:` Replace odd elements in arrays with -1.

In [51]:
# Creating input array
array = np.array([1,2,3,4,5,6,7,8,9,10])

# Replacing odd elements with -1
array = np.where(array%2 != 0,-1,array)

# Printing updated array
print(array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [48]:
# Input arrays
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

# Max element of both the arrays a and b indexwise
ans = np.maximum(a,b)

# Printing max elements of both the arrays a and b indexwise
print(ans)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [41]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8194, 1718, 3291, 7768, 5309],
       [8464, 7462, 7868, 6318, 4257],
       [6737, 4608, 2812, 5393,  920],
       [7132, 6926, 3971, 7303, 1223],
       [1803, 1240, 6375, 4913, 6651],
       [3583, 8941, 2906, 5482, 5268],
       [4187,  627, 2962, 3905, 1576],
       [9073, 3068, 8369, 8359, 1970]])

In [42]:
# Creating normalized array
normalized_array = (arr1 - np.min(arr1)) / (np.max(arr1) - np.min(arr1))

# Printing normalized array
print("Normalized array")
print('\n')
print(normalized_array)

Normalized array


[[0.89592707 0.12917357 0.31541558 0.84548899 0.55434525]
 [0.92789486 0.80925882 0.85732891 0.67381009 0.42978925]
 [0.72341937 0.47134738 0.25870234 0.56429079 0.03469098]
 [0.77018707 0.74579683 0.39592707 0.79043334 0.07056595]
 [0.13923751 0.07257874 0.68055884 0.50745915 0.71323704]
 [0.34998816 0.9843713  0.26983187 0.57482832 0.54949088]
 [0.4215013  0.         0.27646223 0.38811272 0.11236088]
 [1.         0.28901255 0.91664693 0.91546294 0.15901018]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [40]:
# creating function which will give nth largest element of the numpy array
def nth_largest(array,index):

  # Checking condition if index is within limits or not
  if index > len(array):
    print("Sorry but you are trying to access index that is out of bound")

  # Sorting the array
  array = np.sort(array)[::-1]

  # Returning the result
  return array[index-1]


# Input array and index
array = np.array([6,8,4,6,24,4,75,32,325])
index = 4

# Function call
nth_largest(array,index)

24

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [35]:
# Input array from which pattern will be made
a = np.array([1,2,3])

# Creating the pattern
pattern = np.hstack((np.repeat(a,3),np.tile(a,3)))

# Printing pattern
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
